### ISSUE TITLE
Refactoring proposal using Consolidate Duplicate Conditional Fragments technique

### ISSUE THREAD

**Issue by RobertoPatino1** [ericknavarro/ProyectoJavaCC#1]
Let´s see class SimpleCharStream, method ExpandBuff.
Inside this method´s conditional if-else statement there is plenty of identical code on both branches that does not requiere any special value declared inside the branches whatsoever.

Here´s the method before aplying the refactoring technique:
As you can see lines 50,67 - 53,68 - 55,67 - 57,71 - 59,73 are all duplicated.
![image](https://user-images.githubusercontent.com/93289504/184052202-64154e2b-8b33-404d-919c-a1f132a24873.png)

Now let´s take a look at the refactored method
![image](https://user-images.githubusercontent.com/93289504/184051772-bd62329e-22af-4bf4-86dd-99971eb7aa1c.png)

**Comment by ericknavarro** [comment]
This code is generated by [JavaCC](https://javacc.github.io/javacc/), not coded as part of the project, nothing to do on this side, this is part of the JavaCC generator.
