### ISSUE TITLE
Refactoring proposal using Inline Method technique

### ISSUE THREAD

**Issue by RobertoPatino1** [ericknavarro/ProyectoJavaCC#2]
Class Gramatica has 2 unused methods wich can be removed via Inline Method refactoring technique (enable_tracing and disable_tracing) 
Here´s the code before refactoring:
![image](https://user-images.githubusercontent.com/93289504/184053887-0ddd4cb3-2713-487b-b1ad-b7d24101e9a1.png)

Here´s the code after refactoring:
![image](https://user-images.githubusercontent.com/93289504/184053938-00843f01-ea74-4a84-9db3-8ea6c9c04140.png)

**Comment by ericknavarro** [comment]
This code is generated by [JavaCC](https://javacc.github.io/javacc/), not coded as part of the project, nothing to do on this side, this is part of the JavaCC generator.
