### ISSUE TITLE
Refactoring proposal using Encapsulate Fields technique

### ISSUE THREAD

**Issue by RobertoPatino1** [ericknavarro/ProyectoJavaCC#3]
The class Token is basically a data class, wich is not good. It also has all of its fields as public, which is not right if we want to maintain encapsulation in the program. 
By using the encapsulate field technique we guarantee that the client code will have to access the fields on this class via getters, making right use of the access modifiers and making this class a little bit more usefull

Code before refactoring:
![image](https://user-images.githubusercontent.com/93289504/184056137-a2db254e-b3d4-49dd-87e8-9d5f7193bec3.png)

Code after refactoring:
![image](https://user-images.githubusercontent.com/93289504/184056549-1146b84e-e696-4d07-817f-20cd0ff7decd.png)

**Comment by ericknavarro** [comment]
This code is generated by [JavaCC](https://javacc.github.io/javacc/), not coded as part of the project, nothing to do on this side, this is part of the JavaCC generator.
